version: '3.3'

services:
  parrot-service-worker:
    build:
      context: .
      dockerfile: ${PWD}/Dockerfile
    working_dir: /app
    volumes:
      - ./.env:/app/.env
    command: "bash parrot_worker.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]