enable_bucket = true
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5" 
dataset_config = "dataset_config.toml"
resolution = "256,256"
output_dir = "../../../../resources/output" 
network_alpha = 1
save_model_as = "safetensors"
network_module = "networks.lora" 
text_encoder_lr = 0.00001
unet_lr = 2e-4 
output_name = "parrot_lora"        
lr_scheduler_num_cycles = 3
no_half_vae = true 
learning_rate = 1e-4 
lr_scheduler = "cosine" 
train_batch_size = 1
lr_warmup_steps = 0
max_train_epochs = 10
save_every_n_epochs = 2
mixed_precision = "fp16" 
save_precision = "fp16" 
caption_extension = ".txt"  
cache_latents = true
optimizer_type = "Adafactor" 
max_data_loader_n_workers = 0 
flip_aug = true
gradient_checkpointing = true 
xformers = true
bucket_no_upscale = true
max_train_steps=500
